force-app/main/default/objects/Bus__c/fields/Bus_Status__c.field-meta.xml
<CustomField>
    <fullName>Bus_Status__c</fullName>
    <description>Bus status</description>
    <label>Bus Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Limited Seats</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Number_Of_Passengers__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Passengers__c</fullName>
    <label>Number Of Passengers</label>
    <summaryForeignKey>Passenger__c.Bus__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/BusStatusUpdateBatch.cls
public with sharing class BusStatusUpdateBatch implements Database.Batchable<sObject> {
     public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, Name, Number_Of_Passengers__c FROM Bus__c');
    }
     
    public void execute(Database.BatchableContext bc, List<Bus__c> busList) { 
        if(!busList.isEmpty()) {
            update setBusStatus(busList);                                
        }        
    }   
     
    public void finish(Database.BatchableContext bc) {}
    

    private List<Bus__c> setBusStatus(List<Bus__c> busList) {
        List<Bus__c> busesWithNewStatus = new List<Bus__c>();
        for (Bus__c bus : busList) {   
            try {
                if (bus.Number_Of_Passengers__c < 10) {
                    bus.Bus_Status__c = 'Available';
                } else if (bus.Number_Of_Passengers__c >= 10 && bus.Number_Of_Passengers__c < 20) {
                    bus.Bus_Status__c = 'Limited Seats';
                } else if (bus.Number_Of_Passengers__c == 20) {
                    bus.Bus_Status__c = 'Full';
                } else {
                    throw new CustomBusCapacityException('Bus capacity exceeded for ' + bus.Name + ' bus');
                }
                busesWithNewStatus.add(bus);
            } catch (CustomBusCapacityException e) {
                System.debug('Custom exception caught: ' + e.getMessage());
            }           
        }         
        return busesWithNewStatus;
    }
}